# Generated by Django 5.0.6 on 2024-07-29 18:34

import rail.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rail", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="image",
            field=models.ImageField(
                null=True, upload_to=rail.models.train_image_file_path
            ),
        ),
    ]
